package com.PayMyBuddy.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

/**
 * Represent a transaction
 */
@Getter
@Setter
@Entity
@Table(name = "transactions")
public class Transaction {

    /**
     * This defines an id generated by the database as a primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int transactionId;

    @Column(nullable = false)
    private LocalDate date;

    private String description;

    @Column(nullable = false)
    private float amount;

    /**
     * This defines the bidirectional relationship with the model user.
     */
    @ManyToOne(
            cascade = CascadeType.ALL
    )
    @JoinColumn(name="sender_user")
    private User senderUser;

    /**
     * This defines the bidirectional relationship with the model user.
     */
    @ManyToOne(
            cascade = CascadeType.ALL
    )
    @JoinColumn(name="receiver_user")
    private User receiverUser;
}
